{{- if (lookup "v1" "Secret" "emco" "emco-mongo") }}
apiVersion: v1
kind: Secret
metadata:
  name: emcoui-mongo
  namespace: emco 
  labels:
    app: {{ .Values.emcogui.service.label }} 
type: Opaque
data:
  userPassword: {{ (default (randAlphaNum 10) $.Values.global.db.emcouiPassword) | b64enc | quote }}
{{- end }}
